Reusable cards
emmanuellosch/make-less-do-more pull request #14
Opened 2021-03-22 12:23 UTC by emmanuellosch

This PR ist about my User Form. You can upload an Image, your name and write a status like: "Zero Waste Week 33" its the background for building a user profil card and for building a community between the app users. 
Also i changed the "Like-Button" to a heart - some basic styling to get further with the overall style.

2021-03-22 12:59 UTC, mrana17 approved these changes
lgtm 🚀

2021-03-23 08:35 UTC, miriamhaenle requested changes
Hey Emmanuel, I added a few comments in the code.
Please take a look, some of my comments also apply to other documents so I only added it once :)

2021-03-23 08:35 UTC, miriamhaenle commented on client/src/App.js
> +
No commented out code in main! Remove commented out code before merging!

2021-03-23 08:35 UTC, miriamhaenle commented on client/src/App.js
> +//import FileUpload from "./components/UploadComponent";
No commented out code on main ;)

2021-03-23 08:35 UTC, miriamhaenle commented on client/src/GlobalStyles.js
> +  //font-size: 16px;
If you don't need the styles anymore delete it! Commenting out code and pushing it into main just clutters up your codebase. If you want to bring it back you can always check your git history

2021-03-23 08:35 UTC, miriamhaenle commented on client/src/components/RecipeCard.js
>      </Div>
Maybe call the variable `Details` instead of `Text`?

2021-03-23 08:35 UTC, miriamhaenle commented on client/src/components/RecipeCard.js
> +  text-transform: uppercase;
Why do you use the additonal class `.btn` here inside your styled component? 
This is really confusing. Consider to either have two different styled button components or use props to dynamically change the designs that should defer.

2021-03-23 08:35 UTC, miriamhaenle commented on client/src/components/UploadComponent.js
> +import React, { useState, useRef } from "react";
No need to import React
```suggestion
import { useState, useRef } from "react";
```

2021-03-23 08:35 UTC, miriamhaenle commented on client/src/components/UploadComponent.js
> +    }
Does this actually work or maybe throw an error in the console? Usually the rule of hooks suggests not to use hooks inside a javascript function but only from a React functional component

2021-03-23 08:35 UTC, miriamhaenle commented on client/src/pages/Bathroom.js
> +export default function Kitchen() {
The filename says 'Bathroom' but the function says 'Kitchen' ?

2021-03-23 08:35 UTC, miriamhaenle commented on client/src/pages/Bedroom.js
> +export default function Kitchen() {
The filename says 'Bedroom' but the function is called 'Kitchen'?!

2021-03-23 08:35 UTC, miriamhaenle commented on client/src/components/UploadComponent.js
> +      <FileUploadContainer>
Remove the React fragments as the <FileUploadContainer> already wraps the whole content

2021-03-23 08:35 UTC, miriamhaenle commented on client/src/pages/Bathroom.js
> +  const Text = () => (
Details?

2021-03-23 08:35 UTC, miriamhaenle commented on client/src/pages/Bathroom.js
> +const Card = styled.div`
Your are mixing styled components and classNames. This sort of defeats the purpose/advantage of styled components

2021-03-23 08:35 UTC, miriamhaenle commented on client/src/pages/Kidsroom.js
> +export default function Kitchen() {
Kidsroom vs. Kitchen

2021-03-23 08:35 UTC, miriamhaenle commented on client/src/pages/Livingroom.js
> +import React, { useState } from "react";
```suggestion
import { useState } from "react";
```

2021-03-23 08:35 UTC, miriamhaenle commented on client/src/pages/Profil.js
> +  const [formData, setFormData] = useReducer(formReducer, {});
Why did you choose to use the useReducer hook for the form? As it is a rather advanced concept im curious :)

2021-03-23 08:35 UTC, miriamhaenle commented on client/src/pages/Profil.js
> +  const handleSubmit = (event) => {
I've noticed that you called the `event` only `e` in another file. Be consistent when using this. So either always write `event` or always use `e`

2021-03-23 08:35 UTC, miriamhaenle commented on client/src/pages/Profil.js
> +    event.preventDefault();
I think once is enough :)

2021-03-24 08:50 UTC, closed without merging